// National-team captains (source: transfermarkt.com, June 2026)
export const CAPTAINS: Record<string, { name: string; img: string }> = {
  ALG: { name: "Aïssa Mandi", img: '/captains/ALG.jpg' },
  ARG: { name: "Lionel Messi", img: '/captains/ARG.jpg' },
  AUS: { name: "Mathew Ryan", img: '/captains/AUS.jpg' },
  AUT: { name: "David Alaba", img: '/captains/AUT.jpg' },
  BEL: { name: "Youri Tielemans", img: '/captains/BEL.jpg' },
  BIH: { name: "Edin Dzeko", img: '/captains/BIH.jpg' },
  BRA: { name: "Marquinhos", img: '/captains/BRA.jpg' },
  CAN: { name: "Alphonso Davies", img: '/captains/CAN.jpg' },
  CIV: { name: "Franck Kessié", img: '/captains/CIV.jpg' },
  COD: { name: "Chancel Mbemba", img: '/captains/COD.jpg' },
  COL: { name: "James Rodríguez", img: '/captains/COL.jpg' },
  CPV: { name: "Ryan Mendes", img: '/captains/CPV.jpg' },
  CRO: { name: "Luka Modrić", img: '/captains/CRO.jpg' },
  CUW: { name: "Leandro Bacuna", img: '/captains/CUW.jpg' },
  CZE: { name: "Ladislav Krejčí", img: '/captains/CZE.jpg' },
  ECU: { name: "Enner Valencia", img: '/captains/ECU.png' },
  EGY: { name: "Mohamed Salah", img: '/captains/EGY.jpg' },
  ENG: { name: "Harry Kane", img: '/captains/ENG.jpg' },
  ESP: { name: "Rodri", img: '/captains/ESP.jpg' },
  FRA: { name: "Kylian Mbappé", img: '/captains/FRA.jpg' },
  GER: { name: "Joshua Kimmich", img: '/captains/GER.jpg' },
  GHA: { name: "Jordan Ayew", img: '/captains/GHA.jpg' },
  HAI: { name: "Johny Placide", img: '/captains/HAI.png' },
  IRN: { name: "Ehsan Hajsafi", img: '/captains/IRN.png' },
  IRQ: { name: "Jalal Hassan", img: '/captains/IRQ.png' },
  JOR: { name: "Ehsan Haddad", img: '/captains/JOR.jpg' },
  JPN: { name: "Wataru Endo", img: '/captains/JPN.jpg' },
  KOR: { name: "Heung-min Son", img: '/captains/KOR.jpg' },
  KSA: { name: "Salem Al-Dawsari", img: '/captains/KSA.jpg' },
  MAR: { name: "Achraf Hakimi", img: '/captains/MAR.jpg' },
  MEX: { name: "Edson Álvarez", img: '/captains/MEX.jpg' },
  NED: { name: "Virgil van Dijk", img: '/captains/NED.jpg' },
  NOR: { name: "Martin Ødegaard", img: '/captains/NOR.jpg' },
  NZL: { name: "Chris Wood", img: '/captains/NZL.jpg' },
  PAN: { name: "Aníbal Godoy", img: '/captains/PAN.jpg' },
  PAR: { name: "Gustavo Gómez", img: '/captains/PAR.jpg' },
  POR: { name: "Cristiano Ronaldo", img: '/captains/POR.jpg' },
  QAT: { name: "Hasan Al-Haydos", img: '/captains/QAT.jpg' },
  RSA: { name: "Ronwen Williams", img: '/captains/RSA.jpg' },
  SCO: { name: "Andrew Robertson", img: '/captains/SCO.jpg' },
  SEN: { name: "Kalidou Koulibaly", img: '/captains/SEN.png' },
  SUI: { name: "Granit Xhaka", img: '/captains/SUI.jpg' },
  SWE: { name: "Victor Lindelöf", img: '/captains/SWE.jpg' },
  TUN: { name: "Ellyes Skhiri", img: '/captains/TUN.jpg' },
  TUR: { name: "Hakan Çalhanoğlu", img: '/captains/TUR.jpg' },
  URU: { name: "José María Giménez", img: '/captains/URU.jpg' },
  USA: { name: "Tim Ream", img: '/captains/USA.jpg' },
  UZB: { name: "Eldor Shomurodov", img: '/captains/UZB.jpg' },
}
